# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SampleSFSafariViewController' do

# Elegant HTTP Networking in Swift
pod 'Alamofire', '~> 3.1.3'
# - Homepage: https://github.com/Alamofire/Alamofire
# - Source:   https://github.com/Alamofire/Alamofire.git

# SwiftyJSON makes it easy to deal with JSON data in Swift
pod 'SwiftyJSON', '~> 2.3.2'
# - Homepage: https://github.com/SwiftyJSON/SwiftyJSON
# - Source:   https://github.com/SwiftyJSON/SwiftyJSON.git

# Write great asynchronous code in Swift using futures and promises
pod 'BrightFutures', '~> 3.2.2'
# - Homepage: https://github.com/Thomvis/BrightFutures
# - Source:   https://github.com/Thomvis/BrightFutures.git

end

target 'SampleSFSafariViewControllerTests' do

end

target 'SampleSFSafariViewControllerUITests' do

end

